spring.application.name=parkulator-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/parkulator_dev
spring.datasource.username=postgres
spring.datasource.password=parkulator

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=ad1f8c3739be0a8c6142bbe6bd4d2ce90e24fec134ebe56e6c1be36df8ecd3ed